main.c
irtx.c
trigger.c

../common/buzz.c
../common/comm.c
../common/irrx.c
../common/leds.c
../common/led_spi.c
../common/tlc59711.c
../common/malloc.c
../common/mempool.c
../common/phasor_comm.c
../common/serialcomm.c
../common/mpc.c
../common/tasks.c
../common/timer.c
../common/twi_master.c
../common/twi_slave.c
../common/util.c
../common/queue.c
../common/diag.c
